export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const SAVE_USER_DATA_SUCCESS = "SAVE_USER_DATA_SUCCESS";
export const SAVE_USER_DATA_FAILURE = "SAVE_USER_DATA_FAILURE";

// export const SAVE_USER_PROGRESS_SUCCESS = "SAVE_USER_PROGRESS_SUCCESS";
// export const SAVE_USER_PROGRESS_FAILURE = "SAVE_USER_PROGRESS_FAILURE";

// export const SAVE_USER_ACHIEVEMENT_SUCCESS = "SAVE_USER_ACHIEVEMENT_SUCCESS";
// export const SAVE_USER_ACHIEVEMENT_FAILURE = "SAVE_USER_ACHIEVEMENT_FAILURE";

export const GET_ACHIEVEMENTS_SUCCESS = "GET_ACHIEVEMENTS_SUCCESS";
export const GET_ACHIEVEMENTS_FAILURE = "GET_ACHIEVEMENTS_FAILURE";

export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";

export const UPDATE_USER_PROGRESS = "UPDATE_USER_PROGRESS";
